theme: jekyll-theme-cayman
title: "CoFI: Consistency-Guided Fault Injection for Cloud Systems"
description: "Haicheng Chen (The Ohio State University), Wensheng Dou (Chinese Academy of Sciences),<br/>
Dong Wang (Chinese Academy of Sciences), Feng Qin (The Ohio State University)"